CREATE TABLE  IF NOT EXISTS sos_po_receipt_t
(
    po_receipt_no   BIGINT AUTO_INCREMENT
        PRIMARY KEY,
        receipt_det_id BIGINT NULL,
    po_no           BIGINT              NOT NULL,
    po_date         DATE                NOT NULL,
    rm_code         VARCHAR(100)        NOT NULL,
    rm_ord_qty      DECIMAL(11, 2)      NOT NULL,
    rm_received_qty DECIMAL(11, 2)      NOT NULL,
    exp_date_del    DATE                NULL,
    act_date_del    DATE                NULL,
    inspected_by    VARCHAR(100)        NULL,
    approved_by     VARCHAR(100)        NULL,
    invoice_no      VARCHAR(50)         NULL,
    po_det_id       BIGINT              NULL,
    created_by      VARCHAR(100)        NULL,
    created_at      DATETIME            NULL,
    updated_by      VARCHAR(100)        NULL,
    updated_at      DATETIME            NULL,
    is_active       TINYINT(1) DEFAULT 1 NULL,
    is_deleted      TINYINT(1) DEFAULT 0 NULL,
    deleted_by      VARCHAR(100)        NULL,
    deleted_at      DATETIME            NULL
);

CREATE TABLE IF NOT EXISTS sos_material_receipt_t
(
    receipt_id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    receipt_det_id BIGINT NULL,
    material_type      VARCHAR(20)          NULL,
    material_id        BIGINT               NULL,
    no_of_received     INT                  NULL,
    pack_size          INT                  NULL,
    no_of_damaged      INT                  NULL,
    shortage_kgs       DECIMAL(11, 2)       NULL,
    physical_loss      DECIMAL(11, 2)       NULL,
    qty                DECIMAL(11, 2)       NULL,
    per_unit_rate      DECIMAL(11, 2)       DEFAULT 0,
    receipt_main_id    BIGINT               NULL,
    is_fg              TINYINT(1)           DEFAULT 0,
    rm_req_id          BIGINT               NULL,
    shelf_life_time    VARCHAR(100)         NULL,
    pm_account_type_id BIGINT               NULL,
    dom                DATE                 NULL,
    freight_rs         DECIMAL(11, 2)       NULL,
    lot_no             VARCHAR(100)         NULL,
    old_pack_weight    INT                  NULL,
    pack_type          VARCHAR(250)         NULL,
    pack_weight        DECIMAL(11, 2)       NULL,
    po_det_id          BIGINT               NULL,
    po_ref_no          BIGINT               NULL,
    created_by         VARCHAR(100)         NULL,
    created_at         DATETIME             NULL,
    updated_by         VARCHAR(100)         NULL,
    updated_at         DATETIME             NULL,
    is_active          TINYINT(1)           DEFAULT 1 NULL,
    is_deleted         TINYINT(1)           DEFAULT 0 NULL,
    deleted_by         VARCHAR(100)         NULL,
    deleted_at         DATETIME             NULL
);

CREATE TABLE IF NOT EXISTS sos_material_receipt_det_t
(
    receipt_det_id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    material_type            VARCHAR(20)          NULL,
    invoice_no               VARCHAR(100)         NULL,
    warehouse                VARCHAR(100)         NULL,
    description              VARCHAR(500)         NULL,
    sap_po                   VARCHAR(250)         NULL,
    transporter_detls        VARCHAR(500)         NULL,
    transporter_id           BIGINT               NULL,
    freight_rs               DECIMAL(11, 2)       NULL,
    freight_value            DECIMAL(11, 2)       NULL,
    hamali_charges_rs        DECIMAL(11, 2)       NULL,
    vehicle_in               DATE                 NULL,
    vehicle_out              DATE                 NULL,
    unloading_by             VARCHAR(250)         NULL,
    supplier_id              BIGINT               NULL,
    company_id               BIGINT               NULL,
    name_of_transported      VARCHAR(250)         NULL,
    truck_model              VARCHAR(250)         NULL,
    modvat_copy_record       TINYINT(1)           NULL,
    modvat_copy_no           VARCHAR(250)         NULL,
    grn_no                   VARCHAR(250)         NULL,
    irc_no                   VARCHAR(250)         NULL,
    addition_ass_value       DECIMAL(11, 2)       NULL,
    discount                 DECIMAL(5, 2)        NULL,
    discount_value           DECIMAL(11, 2)       NULL,
    cenvat                   DECIMAL(5, 2)        NULL,
    cenvat_value             DECIMAL(11, 2)       NULL,
    addition_duty            DECIMAL(5, 2)        NULL,
    a_d_i_value              DECIMAL(11, 2)       NULL,
    e_cess                   DECIMAL(5, 2)        NULL,
    e_cess_value             DECIMAL(11, 2)       NULL,
    sh_e_cess                DECIMAL(5, 2)        NULL,
    sh_e_cess_value          DECIMAL(11, 2)       NULL,
    c_s_t                    DECIMAL(5, 2)        NULL,
    c_s_t_value              DECIMAL(11, 2)       NULL,
    l_s_t                    DECIMAL(5, 2)        NULL,
    l_s_t_value              DECIMAL(11, 2)       NULL,
    others                   DECIMAL(11, 2)       NULL,
    igst                     DECIMAL(11, 2)       NULL,
    igst_value               DECIMAL(11, 2)       NULL,
    cgst                     DECIMAL(11, 2)       NULL,
    cgst_value               DECIMAL(11, 2)       NULL,
    sgst                     DECIMAL(11, 2)       NULL,
    sgst_value               DECIMAL(11, 2)       NULL,
    invoice_date             DATE                 NULL,
    div_no                   BIGINT               NULL,
    received_by              VARCHAR(100)         NULL,
    driver_name              VARCHAR(250)         NULL,
    receipt_date_time        DATETIME             NULL,
    actual_receipt_date_time DATE                 NULL,
    lr_number                VARCHAR(250)         NULL,
    storage_location         VARCHAR(250)         NULL,
    another_doc_rec          VARCHAR(250)         NULL,
    from_record              TINYINT(1)           NULL,
    excise_complete          TINYINT(1)           NULL,
    remark                   VARCHAR(250)         NULL,
    created_by               VARCHAR(100)         NULL,
    created_at               DATETIME             NULL,
    updated_by               VARCHAR(100)         NULL,
    updated_at               DATETIME             NULL,
    is_active                TINYINT(1)           DEFAULT 1 NULL,
    is_deleted               TINYINT(1)           DEFAULT 0 NULL,
    deleted_by               VARCHAR(100)         NULL,
    deleted_at               DATETIME             NULL
);